### ISSUE TITLE
Add implicit helper for path

### ISSUE THREAD

**Issue by vitamon** [ceedubs/ficus#19]
We found it quite handy to read a bunch of variables from some implicit config like this:
 
 val a = "path.to.variable".as[String]
 val b = "another.path".as[FiniteDuration]
...

Please consider adding simple helper for this, like:

    implicit class ConfigPathHelper(val path: String) {
      def as[T: ValueReader](implicit config: Config): T = {
        config.as[T](path)
      }
    }

**Comment by ceedubs** [comment]
Hi @vitamon. Thanks for the suggestion.

I would advocate using function composition with either `Function1` or something like `Reader`/`Kleisli` from Cats or Scalaz as opposed to passing around an `implicit` `Config` instance. I think that this approach tends to be more composable and less error-prone since you don't have to think about which implicit config might be in scope in a particular section of the code base.

The "Configuration" section of the Cats [Kleisli documentation](http://non.github.io/cats//tut/kleisli.html) has some information on this approach, as does the presentation [Dead-Simple Dependency Injection](https://www.youtube.com/watch?v=ZasXwtTRkio) by Rúnar Óli Bjarnason.

Considering these alternatives, I'm going to go ahead and close out this issue, but I do appreciate you taking the time to make the suggestion.

**Comment by vitamon** [comment]
Usually I have only single implicit config in the scope, so there's nothing to worry about here.
Intention to use the sugar library like this is to simplify the programmers life and improve readability.
Using Kleisli or other DI looks like too much overkill to me.
